### ISSUE TITLE
Top-level command confusing

### ISSUE THREAD

**Issue by esnible** [twosigma/envoy-viz#9]
Confusing

```
go run envoy-viz.go                              
panic: Get "/config_dump": unsupported protocol scheme ""
```

It is confusing that unless `--render dummy` is used, it does not attempt to produce a .dot file, but just writes JSON Envoy config.

Confusing that if --file is used it produces a graph, but if --admin is used it does not even try.

**Comment by blevz** [comment]
Fair, we currently only graph our bootstrap config but I figured for folks that are using the admin option they would want a different rendering option.  I'm still trying to think about the correct cli interface but I'll push an interim solution that sets a sane default for `go run envoy-viz.go` and graphs the bootstrap config returned by the config_dump endpoint when the admin option is specified.  I suspect we should be able to refactor and reuse the bootstrap graphing code to graph the full configu_dump but I'll file a separate issue for that work
